"""add user sessions

Revision ID: be74e9c3231a
Revises: add_student_fee_plan_v2
Create Date: 2026-09-14 10:21:35.228012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be74e9c3231a'
down_revision: Union[str, Sequence[str], None] = 'add_student_fee_plan_v2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_expires_at'), 'user_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_id'), 'user_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_user_sessions_jti'), 'user_sessions', ['jti'], unique=True)
    op.create_index(op.f('ix_user_sessions_revoked_at'), 'user_sessions', ['revoked_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.alter_column('academic_sessions', 'name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.drop_index(op.f('uq_academic_sessions_current_per_school'), table_name='academic_sessions', postgresql_where='(is_current IS TRUE)')
    op.drop_constraint(op.f('uq_admissions_admission_number'), 'admissions', type_='unique')
    op.drop_constraint(op.f('uq_admissions_application_number'), 'admissions', type_='unique')
    op.drop_index(op.f('ix_admissions_admission_number'), table_name='admissions')
    op.create_index(op.f('ix_admissions_admission_number'), 'admissions', ['admission_number'], unique=True)
    op.drop_index(op.f('ix_admissions_application_number'), table_name='admissions')
    op.create_index(op.f('ix_admissions_application_number'), 'admissions', ['application_number'], unique=True)
    op.drop_constraint(op.f('role_permissions_permission_id_fkey'), 'role_permissions', type_='foreignkey')
    op.drop_constraint(op.f('role_permissions_role_id_fkey'), 'role_permissions', type_='foreignkey')
    op.create_foreign_key(None, 'role_permissions', 'roles', ['role_id'], ['id'])
    op.create_foreign_key(None, 'role_permissions', 'permissions', ['permission_id'], ['id'])
    op.alter_column('schools', 'name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('schools', 'phone',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('schools', 'affiliation',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('schools', 'principal_name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('schools', 'logo_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_student_fee_plan_installments_plan_id'), table_name='student_fee_plan_installments')
    op.create_index(op.f('ix_student_fee_plan_installments_student_fee_plan_id'), 'student_fee_plan_installments', ['student_fee_plan_id'], unique=False)
    op.alter_column('student_fee_plan_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('student_fee_plan_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_student_fee_plan_items_active'), table_name='student_fee_plan_items')
    op.drop_index(op.f('ix_student_fee_plan_items_plan_id'), table_name='student_fee_plan_items')
    op.drop_index(op.f('ix_student_fee_plan_items_structure_id'), table_name='student_fee_plan_items')
    op.drop_constraint(op.f('uq_student_fee_plan_item_structure'), 'student_fee_plan_items', type_='unique')
    op.create_index(op.f('ix_student_fee_plan_items_fee_structure_id'), 'student_fee_plan_items', ['fee_structure_id'], unique=False)
    op.create_index(op.f('ix_student_fee_plan_items_student_fee_plan_id'), 'student_fee_plan_items', ['student_fee_plan_id'], unique=False)
    op.alter_column('student_fee_plans', 'status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('student_fee_plans', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('student_fee_plans', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_student_fee_plans_active'), table_name='student_fee_plans')
    op.drop_index(op.f('ix_student_fee_plans_session_id'), table_name='student_fee_plans')
    op.drop_index(op.f('ix_student_fee_plans_status'), table_name='student_fee_plans')
    op.create_index(op.f('ix_student_fee_plans_academic_session_id'), 'student_fee_plans', ['academic_session_id'], unique=False)
    op.drop_constraint(op.f('user_roles_user_id_fkey'), 'user_roles', type_='foreignkey')
    op.drop_constraint(op.f('user_roles_role_id_fkey'), 'user_roles', type_='foreignkey')
    op.create_foreign_key(None, 'user_roles', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'user_roles', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.create_foreign_key(op.f('user_roles_role_id_fkey'), 'user_roles', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('user_roles_user_id_fkey'), 'user_roles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_student_fee_plans_academic_session_id'), table_name='student_fee_plans')
    op.create_index(op.f('ix_student_fee_plans_status'), 'student_fee_plans', ['status'], unique=False)
    op.create_index(op.f('ix_student_fee_plans_session_id'), 'student_fee_plans', ['academic_session_id'], unique=False)
    op.create_index(op.f('ix_student_fee_plans_active'), 'student_fee_plans', ['is_active'], unique=False)
    op.alter_column('student_fee_plans', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('student_fee_plans', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('student_fee_plans', 'status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.drop_index(op.f('ix_student_fee_plan_items_student_fee_plan_id'), table_name='student_fee_plan_items')
    op.drop_index(op.f('ix_student_fee_plan_items_fee_structure_id'), table_name='student_fee_plan_items')
    op.create_unique_constraint(op.f('uq_student_fee_plan_item_structure'), 'student_fee_plan_items', ['student_fee_plan_id', 'fee_structure_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_student_fee_plan_items_structure_id'), 'student_fee_plan_items', ['fee_structure_id'], unique=False)
    op.create_index(op.f('ix_student_fee_plan_items_plan_id'), 'student_fee_plan_items', ['student_fee_plan_id'], unique=False)
    op.create_index(op.f('ix_student_fee_plan_items_active'), 'student_fee_plan_items', ['is_active'], unique=False)
    op.alter_column('student_fee_plan_items', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('student_fee_plan_items', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_student_fee_plan_installments_student_fee_plan_id'), table_name='student_fee_plan_installments')
    op.create_index(op.f('ix_student_fee_plan_installments_plan_id'), 'student_fee_plan_installments', ['student_fee_plan_id'], unique=False)
    op.alter_column('schools', 'logo_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('schools', 'principal_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('schools', 'affiliation',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)
    op.alter_column('schools', 'phone',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.alter_column('schools', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'role_permissions', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'role_permissions', type_='foreignkey')
    op.create_foreign_key(op.f('role_permissions_role_id_fkey'), 'role_permissions', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('role_permissions_permission_id_fkey'), 'role_permissions', 'permissions', ['permission_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_admissions_application_number'), table_name='admissions')
    op.create_index(op.f('ix_admissions_application_number'), 'admissions', ['application_number'], unique=False)
    op.drop_index(op.f('ix_admissions_admission_number'), table_name='admissions')
    op.create_index(op.f('ix_admissions_admission_number'), 'admissions', ['admission_number'], unique=False)
    op.create_unique_constraint(op.f('uq_admissions_application_number'), 'admissions', ['application_number'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_admissions_admission_number'), 'admissions', ['admission_number'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('uq_academic_sessions_current_per_school'), 'academic_sessions', ['school_id'], unique=True, postgresql_where='(is_current IS TRUE)')
    op.alter_column('academic_sessions', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_revoked_at'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_jti'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_expires_at'), table_name='user_sessions')
    op.drop_table('user_sessions')
    # ### end Alembic commands ###
